# Site settings
title: "Kenzie Togami's blogosphere"
email: admin@kenzierocks.me
description: > # this means to ignore newlines until "baseurl:"
  A blog for kenzierocks (Kenzie Togami)
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kenzierocks.me" # the base hostname & protocol for your site
twitter_username: ktogami
github_username:  kenzierocks

# Build settings
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title/
gems:
   - "jekyll-redirect-from"

